# Generated by Django 4.2.2 on 2023-06-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=64)),
                ('user', models.CharField(max_length=64)),
                ('note', models.CharField(max_length=128)),
                ('created', models.DateField()),
                ('due', models.DateField()),
                ('complete', models.BooleanField(default=False, null=True)),
            ],
        ),
    ]
