# Generated by Django 4.2.2 on 2023-06-14 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='complete',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
