# Generated by Django 4.2.2 on 2023-06-14 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_post_created_alter_post_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='note',
            field=models.CharField(max_length=300),
        ),
    ]
