# Generated by Django 4.2.2 on 2023-06-13 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_post_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='urgent',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
