# Generated by Django 4.2.2 on 2023-06-13 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_post_urgent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='urgent',
        ),
    ]
