# Generated by Django 4.2.2 on 2023-06-13 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_post_urgent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='completed',
            new_name='complete',
        ),
    ]
